export const coreInitialization = {
  endpoints: [
    'get_system_status',
    'system_reboot',
    'system_halt',
    'dismiss_system_status',
    'get_system_health',
    'get_memory_usage',
    'get_disk_usage',
    'get_system_temperature',
    'get_cpu_usage',
    'get_system_routes',
    'backup_config',
    'configure_opnsense_connection',
    'search_services',
    'start_service',
    'stop_service',
    'restart_service',
    'get_api_endpoints',
    'exec_api_call',

    'firmware_get_info',
    'firmware_check_updates',
    'firmware_update',
    'firmware_upgrade',
    'firmware_audit',
    'firmware_get_changelog',
    'package_remove',
    'package_reinstall',
    'package_lock',
    'package_unlock',
    'package_get_details',
    'list_plugins',
    'install_plugin',

    'firewall_get_rules',
    'firewall_add_rule',
    'firewall_delete_rule',
    'firewall_toggle_rule',
    'get_firewall_rule',
    'update_firewall_rule',
    'firewall_move_rule',
    'get_firewall_rule_stats',
    'firewall_apply',
    'firewall_savepoint',
    'firewall_revert',
    'perform_firewall_audit',
    'get_firewall_aliases',
    'add_firewall_alias',
    'get_firewall_alias',
    'update_firewall_alias',
    'delete_firewall_alias',
    'toggle_firewall_alias',
    'add_to_alias',
    'delete_from_alias',
    'export_firewall_aliases',
    'import_firewall_aliases',
    'get_alias_table_size',
    'list_alias_contents',
    'flush_alias',
    'get_firewall_logs',

    'get_interfaces',
    'get_interface_details',
    'reload_interface',
    'get_interface_statistics',
    'search_vlans',
    'add_vlan',
    'get_vlan',
    'update_vlan',
    'delete_vlan',
    'reconfigure_vlans',
    'get_arp_table',
    'search_arp_table',
    'flush_arp_table',
    'get_pf_states',
    'query_pf_states',
    'flush_firewall_states',
    'kill_firewall_states',
    'dns_lookup',
    'get_dhcp_config',
    'set_dhcp_config',
    'get_dhcp_status',
    'get_dhcp_leases',
    'search_dhcp_leases',
    'search_dhcp_reservations',
    'add_dhcp_reservation',
    'get_dhcp_reservation',
    'update_dhcp_reservation',
    'delete_dhcp_reservation',
    'toggle_dhcp_reservation',
    'start_dhcp_service',
    'stop_dhcp_service',
    'restart_dhcp_service',
    'reconfigure_dhcp',

    'get_openvpn_instances',
    'search_openvpn_instances',
    'add_openvpn_instance',
    'update_openvpn_instance',
    'delete_openvpn_instance',
    'toggle_openvpn_instance',
    'start_openvpn_service',
    'stop_openvpn_service',
    'restart_openvpn_service',
    'search_openvpn_sessions',
    'kill_openvpn_session',
    'ipsec_is_enabled',
    'toggle_ipsec_service',
    'search_ipsec_connections',
    'add_ipsec_connection',
    'get_ipsec_connection',
    'update_ipsec_connection',
    'delete_ipsec_connection',
    'toggle_ipsec_connection',
    'start_ipsec',
    'stop_ipsec',
    'restart_ipsec',
    'reconfigure_ipsec',
    'search_ipsec_sessions',
    'connect_ipsec_session',
    'disconnect_ipsec_session',

    'search_users',
    'add_user',
    'get_user',
    'update_user',
    'delete_user',
    'search_groups',
    'add_group',
    'get_group',
    'update_group',
    'delete_group',
    'add_api_key',
    'delete_api_key',
    'search_api_keys',
    'search_certificates',
    'add_certificate',
    'get_certificate',
    'delete_certificate',
    'search_certificate_authorities',
    'get_certificate_authority',
    'delete_certificate_authority',

    'get_vpn_connections',
  ],

  tool_categories: {
    'System Management': {
      description: 'Core system operations and monitoring',
      tools: 18,
      subcategories: ['Status & Health', 'Services', 'Configuration', 'API Access'],
    },
    'Firmware & Packages': {
      description: 'Software and package management',
      tools: 13,
      subcategories: ['Firmware Updates', 'Package Management', 'Plugin Installation'],
    },
    'Firewall Operations': {
      description: 'Complete firewall rule and alias management',
      tools: 25,
      subcategories: ['Rules', 'Aliases', 'States', 'Logs', 'Audit'],
    },
    'Network Management': {
      description: 'Interface, VLAN, DHCP, and network diagnostics',
      tools: 33,
      subcategories: ['Interfaces', 'VLANs', 'DHCP', 'Diagnostics', 'ARP/PF States'],
    },
    'VPN Management': {
      description: 'Complete VPN service management',
      tools: 26,
      subcategories: ['OpenVPN', 'IPsec'],
    },
    'User & Security': {
      description: 'Authentication and certificate management',
      tools: 20,
      subcategories: ['Users & Groups', 'API Keys', 'Certificates'],
    },
  },

  api_coverage: {
    core_modules: 8,
    total_endpoints: 135,
    coverage_percentage: '100%',
  },

  security_features: {
    authentication_required: true,
    ssl_verification: 'configurable',
    api_key_rotation: 'supported',
    audit_logging: 'comprehensive',
    backup_safety: 'automatic_savepoints',
  },

  operational_capabilities: {
    read_operations: 'complete',
    write_operations: 'comprehensive',
    bulk_operations: 'supported',
    transaction_safety: 'savepoint_system',
    error_recovery: 'automatic_rollback',
  },
};
